#!/usr/bin/env ruby
dotfiles_dir = File.expand_path(File.dirname(__FILE__))
initial_root = ENV['HOME']
install_scripts_dir = File.expand_path('dotfiles-install-scripts', dotfiles_dir)

def run_scripts(dir, root)
  Dir["#{dir}/*"].select { |path| File.executable?(path) }.each do |script|
    puts "running #{File.basename(script)}"
    `"#{script}" "#{root}"`
  end
end

`./dotfiles-install-symlinks`
run_scripts(install_scripts_dir, initial_root)
