#!/usr/bin/env ruby
require 'pathname'

HOME_DIR = Pathname.new(ARGV[0])

vundle_url = "https://github.com/VundleVim/Vundle.vim.git"
vimdir = HOME_DIR.join('.vim')
bundle_dir = vimdir.join('bundle')
install_dir = bundle_dir.join('Vundle.vim')
`mkdir -p #{bundle_dir}`
# vundle manages updating itself, so we just need to make sure
# that it's there or that we installed it
`git clone "#{vundle_url}" "#{install_dir}"` unless install_dir.directory?
