#!/bin/bash

vimpath=$HOME/.vim/autoload
mkdir -p $vimpath 
if [ ! -f $vimpath/pathogen.vim ]; then
  curl -Sso $vimpath/pathogen.vim \
      https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
fi
