#!/usr/bin/env ruby
HOME_DIR = ARGV[0]

def install!(args, base_dirname, block)
  url = args.pop
  name = args.first || File.basename(url, '.git')
  vimdir = File.expand_path('.vim', HOME_DIR)
  base_dir = File.expand_path(base_dirname, vimdir)
  install_dir = File.expand_path(name, base_dir)
  `mkdir -p #{base_dir}`
  `rm -rf "#{install_dir}" && git clone "#{url}" "#{install_dir}"`
  block.call(install_dir) if block
end

def plugin(*args, &block)
  install!(args, 'bundle', block)
end

def script(*args, &block)
  install!(args, 'scripts', block)
end

plugin 'git://github.com/tpope/vim-rails.git'
plugin 'git://github.com/altercation/vim-colors-solarized.git'
plugin 'git://github.com/tpope/vim-commentary.git'
plugin 'Command-T', 'git://git.wincent.com/command-t.git' do |dir|
  `cd "#{dir}/ruby/command-t" && ruby extconf.rb && make`
end
plugin 'git://github.com/mileszs/ack.vim.git' do
  `which brew && brew install ack`
end
plugin 'actionscript.vim', 'git://github.com/vim-scripts/actionscript.vim--Leider.git'
plugin 'git://github.com/rodjek/vim-puppet.git'
plugin 'git://github.com/othree/html5.vim.git'
