export LC_CTYPE=en_GB.UTF-8
export EDITOR=vim
export GIT_EDITOR="vim -f"
export BUNDLER_EDITOR=vim
export PATH="/usr/local/share/python:/usr/local/share/npm/bin:/usr/local/bin:${PATH}"
export NODE_PATH="/usr/local/lib/node_modules:${NODE_PATH}"
export CLICOLOR=1
export SSL_CERT_FILE=/usr/local/opt/curl-ca-bundle/share/ca-bundle.crt
export GOPATH=/Users/matt/Documents/work/current/go
